### ISSUE TITLE
kataras/go-template/html and dynamic url generation

### ISSUE THREAD

**Issue by Liamraystanley** [kataras/go-template#2]
At this time, [kataras/go-template/html](https://github.com/kataras/go-template/tree/master/html) looks to have support for both shorthand dynamic urls (e.g. `{{ url "sub-page" }}` as documented [here](https://kataras.gitbooks.io/iris/content/routing.html#route-reversing-aka-generating-urls-from-the-route-name)). 

As well as the use of subdomain-style dynamic urls (e.g. `{{ url("dynamic-subdomain1","username1") }}` as shown in an example [here](https://kataras.gitbooks.io/iris/content/template-engines.html))

However, it seems only the use of double quotes works, not single quotes (which makes using it a pain, most people use double quotes for html attributes, having to use double quotes for params in this form breaks syntax highlighting).

For example:

**./test/main.go:**
```go
package main

import (
	"github.com/kataras/go-template/html"
	"github.com/kataras/iris"
)

func main() {
	iris.UseTemplate(html.New()).Directory("./static", ".html")

	iris.Get("/1", func(ctx *iris.Context) { ctx.MustRender("1.html", "") })("first")
	iris.Get("/2", func(ctx *iris.Context) { ctx.MustRender("2.html", "") })("second")

	iris.Listen(":8081")
}
```
**./test/static/1.html:**
```html
this is page 1: {{ url "first" }}
```
**./test/static/2.html:**
```
this is page 2
```

The above works, as does setting **./test/static/1.html** to:
```html
this is page 1: {{ url("first") }}
```

However, the following two do not:
```html
this is page 1: {{ url 'first' }}
```

as well as:
```html
this is page 1: {{ url('first') }}
```

The syntax highlighting issue (amongst other annoying editor issues due to having to use `"` vs. `'`...) is shown below:

![dynamic url syntax bug](http://i.imgur.com/es1uW1S.png)

**Comment by kataras** [comment]
I know my friend but I think I can't do something for this, this is the way how template engines catch string parameters and arguments as far as I know, if you find a better way or other library does it with single quote please write here in order to help me

**Comment by Liamraystanley** [comment]
Looks like this does in fact look to be a limitation of the standard `html/template` library... darn. Well, I'm wondering if a FuncMap function could be used which could pull from named routes. E.g:

```go
iris.Get("/mypath", someHandler)("my-page1")
```

and subsequent `{{ url "my-page1" }}` (outputting `/mypath`). I feel this would be very useful, however it does stray away from the standard url implementation seen in **html/template** (and I don't know if this would override `url()`, or would it just supplement it? -- maybe naming it `{{ route "my-page1" }}`?)

The one thing I'm not a large fan of within the standard `url()`, at least the way it is implemented here, if I start iris bound to `:8080`, it will generate url's as `http://0.0.0.0:8080/some/page`, in which not all platforms support "0.0.0.0" as an IP (Windows, for example, if I'm not mistaken, may be wrong). I think `/some/page` is preferred.

I will poke further when I get the chance and see if there is a better route on how to handle this.

**Comment by Liamraystanley** [comment]
Actually, duh, the other method wouldn't work either. I need more coffee! I'll poke at this further, for now I'm going to close it until I get the chance to poke it further.

**Comment by kataras** [comment]
> and subsequent {{ url "my-page1" }} (outputting /mypath). I feel this would be very useful, however it does stray away from the standard url implementation seen in html/template (and I don't know if this would override url(), or would it just supplement it? -- maybe naming it {{ route "my-page1" }}?)

Just to know we have a `{{urlpath "my-page1" }}` which will give you the `/mypath` you're looking for, I'm asleep so far :)

**Comment by kataras** [comment]
> and subsequent {{ url "my-page1" }} (outputting /mypath). I feel this would be very useful, however it does stray away from the standard url implementation seen in html/template (and I don't know if this would override url(), or would it just supplement it? -- maybe naming it {{ route "my-page1" }}?)

Just to know we have a `{{urlpath "my-page1" }}` which will give you the `/mypath` you're looking for, this lives on template engines examples at: https://github.com/iris-contrib/examples, but they are not specific to this package* I'm asleep so far :)

**Comment by kataras** [comment]
> and subsequent {{ url "my-page1" }} (outputting /mypath). I feel this would be very useful, however it does stray away from the standard url implementation seen in html/template (and I don't know if this would override url(), or would it just supplement it? -- maybe naming it {{ route "my-page1" }}?)

Just to know we have a `{{urlpath "my-page1" }}` which will give you the `/mypath` you're looking for, this lives on template engines examples at: https://github.com/iris-contrib/examples, but these are functions works only inside Iris* I'm asleep so far :)
