### ISSUE TITLE
Vendoring pongo2

### ISSUE THREAD

**Issue by Deluxo** [kataras/go-template#4]
Hello,

I'm here questioning the pongo2 package vendoring.
Why is this choice has been done?

In my opinion, this should be a dependency, since pongo2 is an active project and too complex, to leave it be in vendored state.

Example:

pongo2 allows registering custom filters, which is done with the RegisterFilter().
now if I want to create my custom filter, what I normally do is:
```
import (
	"github.com/kataras/go-template/django"
	"github.com/flosch/pongo2"
        ...
)

func filterTest(in *pongo2.Value, param *pongo2.Value) (*pongo2.Value, *pongo2.Error) {
	return pongo2.AsValue(param.String() + "tested"), nil
}

...
func main() {
	djangoConfig := django.DefaultConfig()
	djangoConfig.Filters["test"] = filterTest
	djangoConfig.DebugTemplates = true
	fw := iris.New()
	fw.Config.IsDevelopment = true
	fw.UseTemplate(django.New(djangoConfig))
}
```

the result of this is the following:
```
cannot use filterTest
(type func(*"github.com/flosch/pongo2".Value, *"github.com/flosch/pongo2".Value)
(*"github.com/flosch/pongo2".Value, *"github.com/flosch/pongo2".Error))
as type "github.com/kataras/go-template/vendor/github.com/flosch/pongo2".FilterFunction
in assignment
```

as you can see, it's a bad'ol packaging hell.
Any ideas on how to fix this? is vendoring really what we are aiming here for?

**Comment by kataras** [comment]
You've absolute right, I'll fix it right now

**Comment by kataras** [comment]
You've absolutely right, I just fixed it(only pongo2 removed because other engines don't have any special attribute which you,as user, should import to use)
