### ISSUE TITLE
 concurrent map writes when debug

### ISSUE THREAD

**Issue by icoder528** [kataras/go-template#5]
It will  encounter concurrent map fatal when the Engine LoadDirectory with development .

**Comment by icoder528** [comment]
`fatal error: concurrent map writes

goroutine 11488 [running]:
runtime.throw(0x1397be7, 0x15)
        C:/GO/src/runtime/panic.go:566 +0x9c fp=0xc0690ceda0 sp=0xc0690ced80
runtime.mapassign1(0x11bca20, 0xc0422c50e0, 0xc0690cefd0, 0xc0690cef78)
        C:/GO/src/runtime/hashmap.go:458 +0x8f6 fp=0xc0690cee88 sp=0xc0690ceda0
github.com/kataras/go-template/django.(*Engine).LoadDirectory.func1(0xc060a67ea0, 0x43, 0x1e18280, 0                                                                                    xc068b82720, 0x0, 0x0, 0xc064cb9790, 0xc0690cf0f8)
        D:/Framework/golang/src/github.com/kataras/go-template/django/django.go:94 +0x3e2 fp=0xc0690                                                                                    cf030 sp=0xc0690cee88
`

**Comment by kataras** [comment]
This probaply happens only when you try to use goroutines to load your templates/assets, thing that you should never do, let the templates load before your server's run, in order to catch any panics before serving pages to the client. Anyway this is fixed now for any case :) thanks for the report
